### ISSUE TITLE
How to use fork-awesome fonts with this theme?

### ISSUE THREAD

**Issue by khurshid-alam** [kurt-liao/github-style-plus#14]
I copied example-site content into root folder. And locally running with baseUrl="", (and theme disabled)

I downloaded [fork-awesome](https://forkaweso.me/Fork-Awesome/) font into /static folder of root dir.

```yml
.static/
|-- css
|   |-- brands.css
|   |-- dark.css
|   |-- fontello.css
|   |-- fork-awesome.css
|   |-- frameworks.min.css
|   |-- gitalk.css
|   |-- github-style.css
|   |-- github.min.css
|   |-- light.css
|   |-- syntax.css
|   `-- toc.css
|-- fonts
|   |-- forkawesome-webfont.eot
|   |-- forkawesome-webfont.svg
|   |-- forkawesome-webfont.ttf
|   |-- forkawesome-webfont.woff
|   |-- forkawesome-webfont.woff2
```

Fork-awesome.css

```css
@font-face {
  font-family: 'ForkAwesome';
  src: url('../fonts/forkawesome-webfont.eot?v=1.1.7');
  src: url('../fonts/forkawesome-webfont.eot?#iefix&v=1.1.7') format('embedded-opentype'), url('../fonts/forkawesome-webfont.woff2?v=1.1.7') format('woff2'), url('../fonts/forkawesome-webfont.woff?v=1.1.7') format('woff'), url('../fonts/forkawesome-webfont.ttf?v=1.1.7') format('truetype'), url('../fonts/forkawesome-webfont.svg?v=1.1.7#forkawesomeregular') format('svg');
  font-weight: normal;
  font-style: normal;
}
.fa {
  display: inline-block;
  .....
}
```

Finally adding the stylesheet into `layouts/partials/head.html`

```html
  <link rel="stylesheet" href='{{ "css/dark.css" | absURL }}' />
  <link rel="stylesheet" href='{{ "css/syntax.css" | absURL }}' />
  <link rel="stylesheet" href='{{ "css/fork-awesome.css" | absURL }}' />
```

**However it doesn't work** when using icon class in markdown content

```md
<!--more-->    

<icon class="fa fa-envelope"></icon>
<i class="fa fa-home"></i> Home
```

**Any idea how to make it work ?**
